language: node_js
node_js:
  - "7"
before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install imagemagick
  - npm install
  - mkdir local/files
  - mkdir local/temp
  - /usr/bin/sqlite3 local/db.sqlt < local/db.schema
script:
  - npm run ci
